# Generated by Django 3.2 on 2021-05-12 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_da_empresa', models.CharField(max_length=500)),
                ('cnpj', models.CharField(max_length=30)),
                ('data_de_cadastro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('campo1', models.TextField()),
                ('campo2', models.TextField()),
                ('campo3', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotsapp.cliente')),
            ],
        ),
    ]
