# Generated by Django 3.0.6 on 2021-05-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotsapp', '0002_auto_20210513_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotsapp.Cliente'),
        ),
    ]
